alter session set container = XEPDB1;

CREATE SEQUENCE CNM_OWNER.ELEMENT_ID
    INCREMENT BY 1
    START WITH 1
    NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE CNM_OWNER.LOCATOR_ID
    INCREMENT BY 1
    START WITH 1
    NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE CNM_OWNER.SECTOR_ID
    INCREMENT BY 1
    START WITH 1
    NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE CNM_OWNER.SYSTEM_ID
    INCREMENT BY 1
    START WITH 1
    NOCYCLE
	NOCACHE
	ORDER;

CREATE SEQUENCE CNM_OWNER.TYPE_ID
    INCREMENT BY 1
    START WITH 1
    NOCYCLE
	NOCACHE
	ORDER;

CREATE TABLE CNM_OWNER.SETTING
(
    KEY                VARCHAR2(128 CHAR)  NOT NULL,
    VALUE              VARCHAR2(4000 BYTE) NOT NULL,
    TYPE               VARCHAR2(32 CHAR) DEFAULT 'STRING' NOT NULL,
    DESCRIPTION        VARCHAR2(2048 CHAR) NOT NULL,
    TAG                VARCHAR2(32 CHAR) DEFAULT 'OTHER' NOT NULL,
    WEIGHT             INTEGER DEFAULT 0 NOT NULL,
    CHANGE_ACTION_JNDI VARCHAR2(128 CHAR) NULL ,
    CONSTRAINT SETTING_PK PRIMARY KEY (KEY),
    CONSTRAINT SETTING_CK1 CHECK (TYPE IN ('STRING', 'BOOLEAN', 'CSV')),
    CONSTRAINT SETTING_CK2 CHECK ((VALUE in ('Y', 'N') AND TYPE = 'BOOLEAN') OR TYPE <> 'BOOLEAN')
);

CREATE TABLE CNM_OWNER.SYSTEM_CODE
(
    SYSTEM_CODE_ID       INTEGER NOT NULL,
    S_CODE               CHAR(1 CHAR) NOT NULL,
	DESCRIPTION          VARCHAR2(512 CHAR) NULL,
	STATE                VARCHAR2(24 CHAR) NULL,
	PROPOSED_BY          INTEGER NULL,
    CONSTRAINT SYSTEM_CODE_PK PRIMARY KEY (SYSTEM_CODE_ID),
    CONSTRAINT SYSTEM_CODE_AK1 UNIQUE (S_CODE),
    CONSTRAINT SYSTEM_CODE_CK1 CHECK (REGEXP_LIKE(S_CODE, '[A-Z]{1}', 'c')),
    CONSTRAINT SYSTEM_CODE_CK2 CHECK (STATE IN ('ACCEPTED', 'PROPOSED'))
);

CREATE TABLE CNM_OWNER.TYPE_CODE
(
    TYPE_CODE_ID         INTEGER NOT NULL,
    VV_CODE              CHAR(2 CHAR) NOT NULL,
	DESCRIPTION          VARCHAR2(512 CHAR) NULL,
	SYSTEM_CODE_ID       INTEGER NOT NULL,
	STATE                VARCHAR2(24 CHAR) NULL,
	PROPOSED_BY          INTEGER NULL,
	GROUPING             VARCHAR2(16 CHAR) NULL,
	JSON_ATTRIBUTES      CLOB NULL,
    CONSTRAINT TYPE_CODE_PK PRIMARY KEY (TYPE_CODE_ID),
    CONSTRAINT TYPE_CODE_AK1 UNIQUE (SYSTEM_CODE_ID,VV_CODE),
    CONSTRAINT TYPE_CODE_FK1 FOREIGN KEY (SYSTEM_CODE_ID) REFERENCES CNM_OWNER.SYSTEM_CODE (SYSTEM_CODE_ID) ON DELETE SET NULL,
    CONSTRAINT TYPE_CODE_CK1 CHECK (REGEXP_LIKE(VV_CODE, '[A-Z0-9]{2}', 'c')),
    CONSTRAINT TYPE_CODE_CK2 CHECK (STATE IN ('ACCEPTED', 'PROPOSED'))
);

CREATE TABLE CNM_OWNER.SECTOR_CODE
(
    SECTOR_CODE_ID       INTEGER NOT NULL,
    XX_CODE              CHAR(2 CHAR) NOT NULL,
	DESCRIPTION          VARCHAR2(512 CHAR) NULL,
	STATE                VARCHAR2(24 CHAR) NULL,
	PROPOSED_BY          INTEGER NULL,
	GROUPING             VARCHAR2(16 CHAR) NULL,
    CONSTRAINT SECTOR_CODE_PK PRIMARY KEY (SECTOR_CODE_ID),
    CONSTRAINT SECTOR_CODE_AK1 UNIQUE (XX_CODE),
    CONSTRAINT SECTOR_CODE_CK1 CHECK (REGEXP_LIKE(XX_CODE, '[A-Z0-9]{2}', 'c')),
    CONSTRAINT SECTOR_CODE_CK2 CHECK (STATE IN ('ACCEPTED', 'PROPOSED'))
);

CREATE TABLE CNM_OWNER.LOCATOR_CODE
(
    LOCATOR_CODE_ID      INTEGER NOT NULL,
    YY_CODE              CHAR(2 CHAR) NOT NULL,
	DESCRIPTION          VARCHAR2(512 CHAR) NULL,
	SECTOR_CODE_ID       INTEGER NOT NULL,
	STATE                VARCHAR2(24 CHAR) NULL,
	PROPOSED_BY          INTEGER NULL,
    CONSTRAINT LOCATOR_CODE_PK PRIMARY KEY (LOCATOR_CODE_ID),
    CONSTRAINT LOCATOR_CODE_AK1 UNIQUE (SECTOR_CODE_ID,YY_CODE),
    CONSTRAINT LOCATOR_CODE_FK1 FOREIGN KEY (SECTOR_CODE_ID) REFERENCES CNM_OWNER.SECTOR_CODE (SECTOR_CODE_ID) ON DELETE SET NULL,
    CONSTRAINT LOCATOR_CODE_CK1 CHECK (STATE IN ('ACCEPTED', 'PROPOSED'))
);

CREATE TABLE CNM_OWNER.ELEMENT_CODE
(
    ELEMENT_CODE_ID      INTEGER NOT NULL,
    ZZ_CODE              CHAR(2 CHAR) NOT NULL,
	DESCRIPTION          VARCHAR2(512 CHAR) NULL,
	STATE                VARCHAR2(24 CHAR) NULL,
	PROPOSED_BY          INTEGER NULL,
    CONSTRAINT ELEMENT_CODE_PK PRIMARY KEY (ELEMENT_CODE_ID),
    CONSTRAINT ELEMENT_CODE_AK1 UNIQUE (ZZ_CODE),
    CONSTRAINT ELEMENT_CODE_CK1 CHECK (STATE IN ('ACCEPTED', 'PROPOSED'))
);

create index type_code_in1 on cnm_owner.type_code(grouping);
create index sector_code_in1 on cnm_owner.sector_code(grouping);

alter table cnm_owner.type_code modify lob (json_attributes) (cache);