services:
  oracle:
    extends:
      file: compose.yaml
      service: oracle

  keycloak:
    extends:
      file: compose.yaml
      service: keycloak

  puppet:
    extends:
      file: compose.yaml
      service: puppet

  mailhog:
    extends:
      file: compose.yaml
      service: mailhog

  cnm:
    extends:
      file: compose.yaml
      service: cnm
    build:
      context: .
      dockerfile: Dockerfile