name: CD

on:
  push:
    paths:
      - 'VERSION'

jobs:
  release:
    uses: jeffersonlab/java-workflows/.github/workflows/gh-release.yml@v1
    with:
      files: build/libs/cnm.war
    secrets: inherit

  docker_publish:
    needs:
      - release
    uses: jeffersonlab/container-workflows/.github/workflows/docker-publish.yml@main
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}
    secrets: inherit

  acctest_deploy:
    needs:
      - release
    uses: jeffersonlab/general-workflows/.github/workflows/jlab-deploy-app.yml@v1
    with:
      app: cnm
      env: acctest
      version: ${{ needs.release.outputs.semver }}
    secrets: inherit